Added optional setting http_proxy to push_image
HASwitchPlate/openHASP-custom-component pull request #144
Opened 2024-08-15 09:47 UTC by xNUTx

Original discussion here: https://github.com/HASwitchPlate/openHASP-custom-component/pull/117

I had it in 'main' instead of a separate branch, so it got a little confusing making patches for other things...

Functional it has no changes compared to the original PR.

```This will allow the user to set up an external reverse proxy to have the HA instance operate on HTTPS and push_image use that reverse proxy to avoid using HTTPS traffic processing on the plate.

Besides now working around a bug in the libraries that kills SSL traffic on the plates, it will also allow the plate not to deal with SSL encrypted connections at all (even when it is working again) to save processing power.```

HA Automation Action example:

```data:
  obj: p12b1
  image: >-
    https://myhainstance:portnumber{{
    state_attr('image.doorbell_event_image','entity_picture') }}
  http_proxy: http://internaladdress:portnumber
  width: 480
  height: 320
  fitscreen: 1
target:
  entity_id: openhasp.displayname
enabled: true
action: openhasp.push_image```

2024-08-18 20:29 UTC, dgomes requested changes

2024-08-18 20:29 UTC, dgomes commented on custom_components/openhasp/__init__.py
> +        vol.Optional(ATTR_PROXY): vol.Any(cv.url),
```suggestion
        vol.Optional(ATTR_PROXY): cv.url,
```

2024-08-19 19:56 UTC, dgomes approved these changes
Still don't see the point as discussed in https://github.com/HASwitchPlate/openHASP-custom-component/pull/117 but technically is OK

2024-08-20 11:19 UTC, xNUTx commented
> Still don't see the point as discussed in #117 but technically is OK

If you are really that heartfelt about the naming, feel free to modify it as you see fit. Functionality is what matters, naming is trivial imho.

2024-08-30 06:54 UTC, xNUTx commented
> So,can this be merged or not?

From my point of view, yes.

Technically it can be according to @dgomes.
If he insists on changing the name of the config variables he can choose to do so, I don't care about the naming that much and I personally need this feature in the HA component for it to work properly in my case and I am getting tired of making modifications every time there is an update on HA or it's components overwriting my required changes.

2024-08-30 14:49 UTC, fvanroie commented
I'm not sure I understand the issue myself. I'm preparing for the HA 2024.9.0 release, so it would be a good time to merge.

2024-08-30 14:54 UTC, dgomes commented
just rename it to what it is: `expose_on_address`

2024-08-30 15:38 UTC, xNUTx commented
In my case though, the original image is hosted by HA on https, I actually have a reverse proxy in use to allow http access to the image url...

But again, I don't care anymore. I just need this feature, regardless of naming.

⁣--

Met vriendelijke groeten/Regards,

Barry Schut
a.k.a. [NUT]​

Op 30 aug. 2024 17:16, om 17:16, fvanroie ***@***.***> schreef:
>Okay, so I think I understand it better now. While the functionality is
>there, the naming of this line is not ideal:
>
>[ATTR_PROXY =
>"http_proxy"](https://github.com/xNUTx/openHASP-custom-component/blob/9f3cd3082f2f573b8cb158a3c983149ae1826b5f/custom_components/openhasp/const.py#L95)
>
>As the link is not a *real* proxy server, but it is just being hosted
>on a different link...
>
>Can I offer my 2cents: what about `server_url` or `base_url`? That
>seems to be a more universal
>[naming](https://swagger.io/docs/specification/api-host-and-base-path/)
>of what the feature does.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/HASwitchPlate/openHASP-custom-component/pull/144#issuecomment-2321580624
>You are receiving this because you authored the thread.
>
>Message ID:
>***@***.***>

2024-09-01 12:02 UTC, merged

2024-09-01 12:03 UTC, fvanroie commented
It seems we are running in circles here...